version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sa@Passw0rd
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - taskmanagement-network

  api:
    build:
      context: .
      dockerfile: src/TaskManagement.API/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=TaskManagementDb;User Id=sa;Password=sa@Passw0rd;TrustServerCertificate=true;
    depends_on:
      - sqlserver
    networks:
      - taskmanagement-network

volumes:
  sqlserver_data:

networks:
  taskmanagement-network:
    driver: bridge
